### ISSUE TITLE
[Chore] 코드 수정 및 View 연결

### ISSUE THREAD

**Issue by mcrkgus** [NOW-SOPT-APP5-KakaoPay/KakaoPay-iOS#17]
## 🛠 Issue

- 전체적인 코드 수정 

## 📝 To-do

- [x] 불필요한 파일 삭제
- [x] icon 전부 다시 추가 및 폴더링 
- [x] navigation Bar Custom
- [x] View 연결
- [x] Home View
