### ISSUE TITLE
[Feat] 자산 화면 collectionView 구현

### ISSUE THREAD

**Issue by Johyerin** [NOW-SOPT-APP5-KakaoPay/KakaoPay-iOS#8]
## 🛠 Issue

- 자산 화면에 들어갈 메인 collectionView 구현

## 📝 To-do

- [x] 모은 돈 섹션
- [x] 계좌 섹션
- [x] 소식 섹션
- [x] 쓴 돈 섹션
- [x] 투자한 돈, 빌린 돈 재사용 셀
- [x] 작지만 큰 차이(?) 섹션
- [x] 자산 바로가기 섹션
- [x] Footer
